In [1]:
import pandas as pd
from matplotlib import pyplot as plt
import seaborn as sns
from scipy import stats
import tensorboard as tb

In [2]:
experiment_id = "c1KCv3X3QvGwaXfgX1c4tg"
experiment = tb.data.experimental.ExperimentFromDev(experiment_id)
df = experiment.get_scalars()
df

                       run             tag  step     value
0         adam,run_1/train  epoch_accuracy     0  0.966867
1         adam,run_1/train  epoch_accuracy     1  0.986283
2         adam,run_1/train  epoch_accuracy     2  0.989333
3         adam,run_1/train  epoch_accuracy     3  0.991933
4         adam,run_1/train  epoch_accuracy     4  0.991733
...                    ...             ...   ...       ...
1195  sgd,run_5/validation      epoch_loss    15  0.020157
1196  sgd,run_5/validation      epoch_loss    16  0.020212
1197  sgd,run_5/validation      epoch_loss    17  0.020364
1198  sgd,run_5/validation      epoch_loss    18  0.022192
1199  sgd,run_5/validation      epoch_loss    19  0.032140

[1200 rows x 4 columns]

In [3]:
dfw = experiment.get_scalars(pivot=True) 
dfw

                      run  step  epoch_accuracy  epoch_loss
0        adam,run_1/train     0        0.966867    0.110196
1        adam,run_1/train     1        0.986283    0.042437
2        adam,run_1/train     2        0.989333    0.032622
3        adam,run_1/train     3        0.991933    0.026121
4        adam,run_1/train     4        0.991733    0.024742
..                    ...   ...             ...         ...
595  sgd,run_5/validation    15        0.993800    0.020157
596  sgd,run_5/validation    16        0.993500    0.020212
597  sgd,run_5/validation    17        0.993800    0.020364
598  sgd,run_5/validation    18        0.993100    0.022192
599  sgd,run_5/validation    19        0.990800    0.032140

[600 rows x 4 columns]

In [5]:
csv_path = 'tb_experiment_1.csv'
dfw.to_csv(csv_path, index=False)